export enum FirebaseCollections {
  USERS = 'users',
  REFERRALS = 'referrals',
  DEPOSITS = 'deposits',
  BANK = 'banks',
  CURRENCIES = 'currencies',
  WALLETS = 'wallets',
  ASSETS = 'assets',
  MARKET_PAIRS = 'market_pairs',
  EXCHANGES = 'exchanges',
  ORDERS = 'orders',
  FEES = 'fees',
  ADDRESSES = 'addresses',
  CRYPTO_DEPOSITS = 'crypto_deposits',
  PRESALE_COINS = 'presale_coins',
  PRESALE_ORDERS = 'presale_orders',
  PRESALE_ASSETS = 'presale_assets',
  NFT_PRESALE_TOKENS = 'nft_presale_tokens',
  NFT_PRESALE_ORDERS = 'nft_presale_orders',
  NFT_PRESALE_ASSETS = 'nft_presale_assets',
}
