export type Features =
  | 'sign_in'
  | 'sign_up'
  | 'forgot_password'
  | 'deposit_fiat'
  | 'deposit_crypto'
  | 'buy_sell'
  | 'dashboard'
  | 'coin_list'
  | 'coin_register'
  | 'wallet'
  | 'presale_coins'
  | 'presale_nfts'
  | 'equities'
  | 'equities_register';
