import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Knights</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://kxco.io/assets/img/favicon.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hold on brave Knight!
        </h1>
        <h2 className={styles.title}> We are updating the <a href="https://kxco.io">Knightbridge!</a></h2>

        <p className={styles.description}>
          Meanwhile visit our {' '}
          <code className={styles.code}><a href="https://t.me/knightsDAO">Telegram!</a></code>
        </p>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by The Keepers of the code!
          
        </a>
      </footer>
    </div>
  )
}

export default Home
